image: Visual Studio 2015
version: "1.0.0.{build}"
configuration:
  - Release

init:
  - git config --global core.autocrlf input
  - ps: $Env:LABEL = $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

test: off

before_build:
  - dotnet restore -v minimal

build:
  project: Swashbuckle.AspNetCore.sln
  parallel: true
  verbosity: minimal

after_build:
  - dotnet pack -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts .\src\Swashbuckle.AspNetCore.Swagger\project.json
  - dotnet pack -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts .\src\Swashbuckle.AspNetCore.SwaggerUi\project.json
  - dotnet pack -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts .\src\Swashbuckle.AspNetCore.SwaggerGen\project.json

artifacts:
  - path: artifacts\*.nupkg

deploy:
  - provider: NuGet
    server: https://novaworks.myget.org/F/public/api/v2/package
    api_key:
      secure: 8CsS42Ic+vTW/DhHUAJ5KreTtOCnHDvzPwLJebjUQelchOvjhskEZFJ4EIR9tV3F
    skip_symbols: false
    symbol_server: https://novaworks.myget.org/F/public/symbols/api/v2/package
    artifact: /.*\.nupkg/