image: Visual Studio 2015
version: "1.0.0.{build}"
configuration:
  - Release

init:
  - git config --global core.autocrlf input

install:
  - ps: .\ReleaseVersion.ps1  

assembly_info:
  patch: true
  file: SharedAssemblyInfo.cs
  assembly_version: $(appveyor_build_version)
  assembly_file_version: $(appveyor_build_version)
  assembly_informational_version: $(appveyor_build_version)

test: off

before_build:
  - dotnet restore -v minimal

build:
  project: Swashbuckle.AspNetCore.sln
  parallel: true
  verbosity: minimal

after_build:
  - ps: .\CreatePackages.ps1

artifacts:
  - path: artifacts\*.nupkg

deploy:
  - provider: NuGet
    server: https://novaworks.myget.org/F/public/api/v2/package
    api_key:
      secure: 8CsS42Ic+vTW/DhHUAJ5KreTtOCnHDvzPwLJebjUQelchOvjhskEZFJ4EIR9tV3F
    skip_symbols: false
    symbol_server: https://novaworks.myget.org/F/public/symbols/api/v2/package
    artifact: /.*\.nupkg/